spring:
  application:
    name: strong_junior_test_task

  sql:
    init:
      mode: never

  datasource:
    url: jdbc:postgresql://localhost:5432/products_order
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

jwt:
  secret-key: "753778214125442A472D4B6150645367566B59703373367639792F423F452848"
  expire-timeout: 36000000

server:
  servlet:
    context-path: /ecommerce